### ISSUE TITLE
Sample

### ISSUE THREAD

**Issue by Hitexroid** [dda410/subtitlesToScreen#1]
Hi , Can you post a simple sample ?

**Comment by dda410** [comment]
Hi Hitexroid,

After cloning the repository you need to compile the source files under the subsToScreen folder (under /subtitlesToScreen/src/subsToScreen) with:
`javac subsToScreen/*.java`
You can then run the program by running the main class:
`java subsToScreen.Main /path/To/your/srt/file`
If you go through the read me file you can see how to use also the two other optional arguments (the time start time of the subtitles to be played argument and the delay argument).
Something like:
`java subsToScreen.Main /home/user/Documents/subtitleFiles/mySrtFile.srt 00:35:25,000 +05,250`
it plays the .srt file from 35th minute, 25th second and 0 milliseconds with 5 seconds and 250 milliseconds delay.
